### ISSUE TITLE
could you be so kind as to provide a conda package for tdameritrade package?  

### ISSUE THREAD

**Issue by richdevboston** [timkpaine/tdameritrade#106]
Hi Tim, 

Thank you for your tdameritrade package is very nice and clean.  The API is conceptually direct and streamlined. 

I know this might be viewed as primarily a preference issue, but (if you use conda) could you please be so kind as to provide a conda package for your tdameritrade package?   

I use conda whenever possible, because it does environment consistency checking that pip does not.  I have had quite a few problems by installing pip packages (using pip) into my conda environments and then the conda package index gets out of sink, corrupting things.  It then requires a precious time to fix things or rebuild a new environment.  There is still a problem with interleaving pip and conda packages into a conda environment.  We need a better tool with the advantages of both the pip package managers and the conda environment manager.  I don't (yet) know how to convert pip to conda packages, or if there's a reliable pip to conda package converter.  Perhaps you know of an easy fix for this besides using pip only?  

Thank you.  

Best Regards, 

Rich Lysakowski

**Comment by timkpaine** [comment]
https://github.com/conda-forge/tdameritrade-feedstock
`conda install -c conda-forge tdamertrade`
