### ISSUE TITLE
Guidance on 429 response code handling

### ISSUE THREAD

**Issue by j20120307** [timkpaine/tdameritrade#110]
I'm seeing 429 status code from getQuote API with authentication. AFAIK, real-time quote info requires authenticated request, which falls in the restriction of throttling [1]. Any guidance on next steps? Any plan for rate limiting support?

[1] https://developer.tdameritrade.com/content/authentication-faq

**Comment by wilfredcho** [comment]
your application should take care of that, the client code is just there to make calls.

try using ratelimit https://pypi.org/project/ratelimit/
