### ISSUE TITLE
int vs str on stopPrice

### ISSUE THREAD

**Issue by nsinenian** [timkpaine/tdameritrade#112]
orders.py has the following comment:

        Notes:
                The int fields may not be actual ints even though the docs use an int as the default.
                When I checked the sample orders, they made price into a string e.g., "6.45".
        
                I made price a str for now.
            """

The 'stopPrice' and 'stopPriceOffset' are specified as integers in the Order class, while the `price` (e.g., limit price) is specified as a string. 

Any reason for this insanity?  

Despite the comment above (which is bad practice to begin with), prices cannot be specified as strings else exceptions are thrown. Maybe there's something I'm missing about the API(?) but regardless of API inconsistencies I think the interface should be made consistent.

**Comment by timkpaine** [comment]
To start, I recommend reading [writing the perfect question](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/), in particular the section entitled "Making a good impression". "Above all, be polite. Remember that no-one is getting paid to answer your question. Users are giving up their time to help you – so please be appreciative of that. "

If you have suggested changes, feel free to suggest them or make a pull request with them. I don't use this particular code block, and the TD documentation and API design choices are not always the most sound. A quick look through the [samples](https://developer.tdameritrade.com/content/place-order-samples) shows all prices as strings in the json messages, so its reasonable to me that the order builder make them all strings as well. At the end of the day, the order builder is merely a convenience, and when you place orders you can simply provide a python dictionary.
