### ISSUE TITLE
401 response, could not authenticate

### ISSUE THREAD

**Issue by Depth2465** [timkpaine/tdameritrade#116]
I followed all of the authentication steps outlined here: https://tdameritrade.readthedocs.io/en/latest/index.html
-but I keep getting a 401 response from the auth access_token function. I edited the function to print out my client_id and refresh_token, and everything looks in order. But the response comes back 401.

I went here: https://developer.tdameritrade.com/authentication/apis/post/token-0
-and put the same information in the body parameters, and when I click SEND it gives me the correct 200 OK response.

Any reason why this would be? Any help is appreciated.

**Comment by timkpaine** [comment]
Almost certainly a typo or something similar, we've had issues reported here in the past where the problem was something like `https://localhost:8000` instead of `http://localhost:8000`, or trailing spaces or similar things
