### ISSUE TITLE
Option chain data returning call volatility for both put and call for a given strike and expiration

### ISSUE THREAD

**Issue by churchec** [timkpaine/tdameritrade#117]
c.optionsDF and c.options are returning the same volatility for both put and call options for a given expiration and strike price. I checked the source data using TD api website, and the source data is correct.

**Comment by timkpaine** [comment]
This is just an API pass-through, if the data coming off the API is wrong you should reach out to TD support

**Comment by churchec** [comment]
The data coming from the API is correct.

**Comment by timkpaine** [comment]
Then there's no bug. We literally just wrap with `requests` https://github.com/timkpaine/tdameritrade/blob/master/tdameritrade/client.py#L372

**Comment by churchec** [comment]
The data coming off of the API is correct. The output of volatility for put options using c.options and c.optionsDF is incorrect. The volatility of the call options is being shown for both the put and the call for a given strike and expiry.

**Comment by timkpaine** [comment]
Look at the code, `options` returns the raw results from the api. There are no transforms. If the output is wrong, the data off the api is wrong

**Comment by churchec** [comment]
Yep, you are totally right. The data from the API is the issue - I compared data incorrectly. Sorry! Thanks for all your work on this!

**Comment by timkpaine** [comment]
The TD support people are very helpful, they should be able to fix things right away
