### ISSUE TITLE
refresh_token fails to authenticate

### ISSUE THREAD

**Issue by chaimpeck** [timkpaine/tdameritrade#12]
https://github.com/timkpaine/tdameritrade/blob/6bc7f8fdac84551b7408ac55347d0ddd7008063b/tdameritrade/auth/__init__.py#L77

Suggested fix:
```
def refresh_token(refresh_token, client_id):
    resp = requests.post('https://api.tdameritrade.com/v1/oauth2/token',
                         headers={'Content-Type': 'application/x-www-form-urlencoded'},
                         data={'grant_type': 'refresh_token',
                               'refresh_token': refresh_token,
                               'client_id': client_id})
    if resp.status_code != 200:
        raise Exception('Could not authenticate!')
    return resp.json()
```

Note, I am passing data in `data` - not `json`. And not quoting the token or client_id.

I made this change locally and it works for me.

**Comment by kevmartian** [comment]
Thank you @chaimpeck - i've been struggling with this all day and figured I was doing something wrong when passing the data. This fixed it.

**Comment by timkpaine** [comment]
should be good now
