### ISSUE TITLE
accounts report errored out

### ISSUE THREAD

**Issue by Oriono** [timkpaine/tdameritrade#132]
**Describe the bug**
when requesting account positions, it failed. But other operations like pulling optionDF, watchlists and historyDF still working

**To Reproduce**
1. getting accout position with tdclient.accounts()
2. See error

**Expected behavior**
returning my account info 

**Screenshots**

![image](https://user-images.githubusercontent.com/4912632/106421632-e5597980-6411-11eb-94ea-6572fbe3dfb8.png)

**Desktop (please complete the following information):**
 - OS: Mac Pro Catalina

**Comment by qililiu** [comment]
Hello, I have the same error as described above. Can anyone help us to resolve it?

**Comment by zachlim98** [comment]
Yup, can confirm having same error. Thanks for any help

**Comment by Oriono** [comment]
Fixed.  in TDClient, we shouldn't include only one Account ID, that will error out anything related to accounts method. 
so instead of tdclient = td.TDClient(client_id,refresh_token,account_id)
do tdclient = td.TDClient(client_id,refresh_token).
