### ISSUE TITLE
TDAMERITRADE_ACCOUNT_ID?

### ISSUE THREAD

**Issue by duncanmcdonald** [timkpaine/tdameritrade#138]
What is the TDAMERITRADE_ACCOUNT_ID? TD Ameritrade has a user id and an account number so I'm not sure what you mean by account id.

**Comment by alelasantillan** [comment]
I have the same problem. In my opinion TDAMERITRADE_ACCOUNT_ID refers to the account number.

**Comment by duncanmcdonald** [comment]
I’m trying a different approach right now, but will come back to this code
in a month or so.
