### ISSUE TITLE
Orders with 'extended' time in force

### ISSUE THREAD

**Issue by rodrigobell** [timkpaine/tdameritrade#143]
Browsing through the docs, I'm not seeing an option to place an order after-hours. Is this not an option offered by tdameritrade, or did I miss something?

I'm not seeing it under https://developer.tdameritrade.com/content/place-order-samples either.

**Comment by timkpaine** [comment]
Not everything is supported by their API, but their support team is pretty responsive and may tell you how to do it. If its something thats possible, we can add it here.
