### ISSUE TITLE
No positions show?

### ISSUE THREAD

**Issue by dahifi** [timkpaine/tdameritrade#18]
I'm not seeing my actual positions listed in my client.accounts(). 

Might have something to do with the fact that this is an IRA? 

```
{
    "x": {
        "securitiesAccount": {
            "accountId": "x",
            "currentBalances": {
                "accruedInterest": 0.0,
                "bondValue": 0.0,
                "cashAvailableForTrading": x,
                "cashAvailableForWithdrawal": x,
                "cashBalance": 0.0,
                "cashCall": 0.0,
                "cashDebitCallValue": 0.0,
                "cashReceipts": 0.0,
                "liquidationValue": x,
                "longMarketValue": x,
                "longNonMarginableMarketValue": x,
                "longOptionMarketValue": 0.0,
                "moneyMarketFund": x,
                "pendingDeposits": 0.0,
                "savings": 0.0,
                "shortMarketValue": 0.0,
                "shortOptionMarketValue": 0.0,
                "totalCash": 0.0,
                "unsettledCash": 0.0
            },
            "initialBalances": {
                "accountValue": x,
                "accruedInterest": 0.0,
                "bondValue": 0.0,
                "cashAvailableForTrading": x,
                "cashAvailableForWithdrawal": x,
                "cashBalance": x,
                "cashDebitCallValue": 0.0,
                "cashReceipts": 0.0,
                "isInCall": false,
                "liquidationValue": x,
                "longOptionMarketValue": 0.0,
                "longStockValue": x,
                "moneyMarketFund": x,
                "mutualFundValue": 0.0,
                "pendingDeposits": 0.0,
                "shortOptionMarketValue": 0.0,
                "shortStockValue": 0.0,
                "unsettledCash": 0.0
            },
            "isClosingOnlyRestricted": false,
            "isDayTrader": false,
            "projectedBalances": {
                "cashAvailableForTrading": x,
                "cashAvailableForWithdrawal": x
            },
            "roundTrips": 0,
            "type": "CASH"
        }
    }
}

``

**Comment by timkpaine** [comment]
https://developer.tdameritrade.com/account-access/apis/get/accounts-0 
Will return data for cash and margin accounts. probably doesn't include IRA.

**Comment by dahifi** [comment]
Says right in my JSON that it's a cash account. I'll see if I can reach out to the TD dev team for clarification.

**Comment by dahifi** [comment]
So, based on the API docs, positions and orders are available via the account API through the use of a field query. If you don't include the field, you get the account summary info I displayed earlier. 

I've modified the account function as follows: 

'''
    def accounts(self, positions=False, orders=False):
        ret = {}

        if positions or orders:
            fields = '?fields='
            if positions:
                fields += 'positions'
                if orders:
                    fields += ',orders'
            elif orders:
                fields += 'orders'
        else:
            fields = None

        if self.accountIds:
            for acc in self.accountIds:
                resp = requests.get(ACCOUNTS + str(acc) + fields, headers=self._headers())
                if resp.status_code == 200:
                    ret[acc] = resp.json()
                else:
                    raise Exception(resp.text)
        else:
            resp = requests.get(ACCOUNTS + fields, headers=self._headers())
            if resp.status_code == 200:
                for account in resp.json():
                    ret[account['securitiesAccount']['accountId']] = account
            else:
                raise Exception(resp.text)
        return ret
'''
