### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by rsadr** [timkpaine/tdameritrade#23]
There is no such a class in this package called for in 

tdameritrade.auth.authentication

**Comment by timkpaine** [comment]
Yeah its right here:
https://github.com/timkpaine/tdameritrade/blob/master/tdameritrade/auth/__init__.py#L11

**Comment by feapri** [comment]
@rsadr
some time ago I was receiving the same error message and I realize that I was missing the import part....
    import tdameritrade
    tdameritrade.auth.authentication ('your_OAuth_User_ID', 'http://localhost:8080')
that solved the authentication problem for me.

one other thing that wasn't clear enough (to me at least) was the role the refresh_token plays and how to use it.
in a nut shell:
upon authentication, the output will be a dictionary like:
{'access_token': 'bBjBD', 'refresh_token': '/z3ObP9G', 'expires_in': 1800, 'refresh_token_expires_in': 7776000, 'token_type': 'Bearer'}

- the access_token is valid for 30 minutes (1800 seconds / 60 seconds/minute )  = 30 minutes
- the refresh_token is valid for 90 days (7776000 seconds / 24 hrs / 60 min / 60 seconds) = 90 days
- the refresh_token can be used to generate new access_token without having to authenticate.

I ended up having 2 files (I kept these in different folders):
- one to store the access_token (at.tkn)  (I'm planning to get rid of this one as the refresh_token takes care of the needs)
- one to store the refresh_token (rt.tkn)

This is what I do every 90 days:

        import tdameritrade
        d = tdameritrade.auth.authentication ('your_OAuth_User_ID', 'http://localhost:8080')
        (authenticate in the new browser window)

        # save the tokens...
        with open ('C:/.../at.tkn', 'w') as f:
            f.write(d['access_token'])

        with open ('C:/.../rt.tkn', 'w') as f:
            f.write(d['refresh_token'])


on a regular basis, I do use the refresh_token to get a new access_tokenas as follows:

    def newAccessToken():
        global access_token
        refresh_token = open ('path_to_rt', 'r').read()
        access_token = auth.refresh_token(refresh_token, 'your_OAuth_User_ID')['access_token']

    newAccessToken()
    c = td.TDClient(access_token)
    c.optionsDF('ROM').shape

by doing this, I do not need to authenticate every 30 minutes but every 90 days.
hope this helps to solve the issue you are experincing and to improve the documentation.

**Comment by rsadr** [comment]
Thanks to "feapri" for excellent clarification on refresh_token and session lifecycle.

I had success after Tim's kind input. 

I would recommend to add the followings to installation instruction:

1. import TDAmeritrade.auth (explicitly) in step 5
2. Add Selenium and browser driver (I chose Chrome driver) required in /usr/lib/bin on Linux

**Comment by rsadr** [comment]
Dear Tim-

I very much appreciate as we have consistantly used your library for the
past year without a glitch.. However, recently we have been for days
struggling to use you library to place an order for a vertical spread
without any success.

We would greatly appreciate if you can tell us if we are passing anything
wrong. We continue to get 400 error code (ret=c.orders(account_id,order).

FYI, we have reached out to api@tdameritrade.com, but they have been
completely unresponsive. We are not sure it is ue to their complacency or
due to COViD-19 situation.

Below is the json structure we are passing (order).

We look forward to hearing from you.

Best regards,
-Ramin
Dr Ramin Sadr
LA, Ca, 90077
Cell: 818-292-4099











___________________

{'session': 'NORMAL',
 'duration': 'DAY',
 'orderType': 'LIMIT',
 'cancelTime': {'date': 'string', 'shortFormat': 'false'},
 'complexOrderStrategyType': 'VERTICAL',
 'quantity': 0,
 'filledQuantity': 0,
 'remainingQuantity': 0,
 'requestedDestination': 'AUTO',
 'destinationLinkName': '',
 'releaseTime': '',
 'stopPrice': 0,
 'stopPriceLinkBasis': 'MANUAL',
 'stopPriceLinkType': 'VALUE',
 'stopPriceOffset': 0,
 'stopType': 'STANDARD',
 'priceLinkBasis': 'MANUAL',
 'priceLinkType': 'VALUE',
 'price': 0.41,
 'taxLotMethod': ' ',
 'orderLegCollection': [{'orderLegType': 'OPTION',
   'legId': 1,
   'instrument': {'Symbol': 'SPY_041320P266', 'assetType': 'OPTION'},
   'instruction': 'SELL_TO_OPEN',
   'positionEffect': 'AUTOMATIC',
   'quantity': 10,
   'quantityType': 'ALL_SHARES'},
  {'orderLegType': 'OPTION',
   'legId': 2,
   'instrument': {'Symbol': 'SPY_041320P258', 'assetType': 'OPTION'},
   'instruction': 'BUY_TO_OPEN',
   'positionEffect': 'AUTOMATIC',
   'quantity': 10,
   'quantityType': 'ALL_SHARES'}],
 'activationPrice': 0,
 'specialInstruction': 'ALL_OR_NONE',
 'orderStrategyType': 'SINGLE',
 'orderId': 0,
 'cancelable': 'true',
 'editable': 'true',
 'status': 'AWAITING_MANUAL_REVIEW',
 'enteredTime': 'string',
 'closeTime': 'string',
 'tag': 'string',
 'accountId': 686024253,
 'orderActivityCollection': '[]',
 'replacingOrderCollection': [{}],
 'childOrderStrategies': [{}],
 'statusDescription': ''}
