### ISSUE TITLE
Exception: { "error":"The access token being passed has expired or is invalid."       		}

### ISSUE THREAD

**Issue by lmsanch** [timkpaine/tdameritrade#25]
Yesterday, I was able to get the library to work (I had issues with the selenium part and the location of the executable).
After saving the token and the refresh token, I was able to access al the library's functionality by specifying
`c = client.TDClient("TOKEN")`
Where TOKEN is saved in my environments file.
Today, I am getting the error message above.
I tried the same but with the saved refresh token, getting the same error.
Do I have to get a new token for every session? What's the solution here?
Thanks

**Comment by lmsanch** [comment]
I just found out that TOKEN and REFRESH_TOKEN have expiration times:
`'expires_in': 1800`, that's in epochs, which is equivalent to 30 minutes
Is there any way to request a longer expiration token?

**Comment by timkpaine** [comment]
according to the docs its 30 days?

**Comment by lmsanch** [comment]
They must have changed it. The dictionary says 'expires_in' : 1800, that is 30 minutes
<img width="570" alt="Screen Shot 2019-11-19 at 2 11 40 PM" src="https://user-images.githubusercontent.com/3156487/69177942-8e020e80-0ad6-11ea-8015-f7ce8c636aa5.png">
https://www.epochconverter.com/
It was 90 days, then I think they changed it to 30 days and looks like now is 30 minutes. I guess I will program the token capture function with selenium and/or splinter.

**Comment by lmsanch** [comment]
Do I still use TDClinet with the refresh token?

**Comment by timkpaine** [comment]
I believe the refresh token is only used to get a new access token

**Comment by ccalica** [comment]
I'm doing this:

`from tdameritrade import TDClient
from tdameritrade.auth import refresh_token

refresh = refresh_token(os.environ.get('REFRESH_TOKEN',''), client_id)

c = TDClient(refresh['access_token'])`
