### ISSUE TITLE
History pull

### ISSUE THREAD

**Issue by ecjbosu** [timkpaine/tdameritrade#26]
Are planning on expanding the history to allow for additional inputs, like start date?

**Comment by jrbartola** [comment]
@ecjbosu I've created a pull request (#31) to allow for the `history` request to be sent with [custom query parameters](https://github.com/timkpaine/tdameritrade/blob/152a8b5330aab811cca993c01ab38ce4d4cc9a26/tdameritrade/client.py#L83)
