### ISSUE TITLE
[ENH] Order API endpoints ?

### ISSUE THREAD

**Issue by WillForan** [timkpaine/tdameritrade#29]
Are the `/v1/accounts/{accountId}/orders[/{orderId}]` POST/GET/DELETE endpoints within the scope of this module?

I cannot find any reference to paper trading in the TD Ameritrade docs. That probably makes these pretty dangerous to test out :)

**Comment by timkpaine** [comment]
@WillForan indeed. Happy to have them added but I'm not able to trade.

**Comment by dahifi** [comment]
I implemented orders locally: 

```
    def orders(self, account_id, json_order):
        orders = ACCOUNTS + account_id + "/orders"
        return requests.post(orders,
                             headers=self._headers(),
                             json=json_order
                             )
```

Been using it successfully for a few weeks now. 
Have to pass the accountID.

**Comment by poojankhanpara** [comment]
> I implemented orders locally:
> 
> ```
> client.py: 
>     def orders(self, account_id, json_order):
>         orders = ACCOUNTS + account_id + "/orders"
>         return requests.post(orders,
>                              headers=self._headers(),
>                              json=json_order
>                              )
> ```
> 
> Been using it successfully for a few weeks now.

@dahifi Can you please do a PR?

**Comment by poojankhanpara** [comment]
I tried this order 
`{
	"orderType": "MARKET",
	"session": "NORMAL",
	"duration": "DAY",
	"orderStrategyType": "SINGLE",
	"orderLegCollection": [{
		"instruction": "BUY",
		"quantity": 1,
		"instrument": {
			"symbol": "BAC",
			"assetType": "EQUITY"
		}
	}]
}`
But it is giving me "A validation error occurred while processing the request". It parses fine when I convert it into dict by json.loads().

**Comment by arh** [comment]
Would you please share how can we use this order API:

```
myorder = {
    "session": 'NORMAL',
    "duration": 'DAY',
    "orderType": 'LIMIT',
    "quantity": 1,
    "requestedDestination": 'AUTO',
    "price": '1.1',
    "orderLegCollection": [
        {
            "orderLegType": 'EQUITY',
            "instrument": {
                        "assetType": 'EQUITY' ,
                        "symbol": 'SPY',
                        },
            "instruction": 'BUY',
            "quantity": 1,
            "quantityType": 'SHARES'
        }
    ],
    "orderStrategyType": 'SINGLE'
}
myjson = json.dumps(myorder)
c.orders('6860000002',myjson)
```

It give me this erro:
{'error': 'A validation error occurred while processing the request.'}

**Comment by dahifi** [comment]
I spent a great deal of time trying to take TD's crappy JSON schema and parse it through Quicktype library: http://dahifi.net/2019/11/20/quicktype-and-ameritrades-api/

The code is not ready for prime-time. I'm not quite sure how I would integrate it into this library, but basically it translates JSON into native Python dictionary objects. 

The function I use to place an order is: 
```
def limit_order():
    order = dict(
        {
            "complexOrderStrategyType": "NONE",
            "orderType": "LIMIT",
            "session": "NORMAL",
            "price": price,
            "duration": "GOOD_TILL_CANCEL",
            "orderStrategyType": "SINGLE",
            "orderLegCollection": [
                {
                    "instruction": instruction,
                    "quantity": num_shares,
                    "instrument": {
                        "symbol": symbol,
                        "assetType": "EQUITY"
                    }
                }
            ]
        }
    )
    return order
```
I got the above from the Place Order Samples doc on TD's site: https://developer.tdameritrade.com/content/place-order-samples

If y'all can give me a few days I'll try to get the orders function in a proper PR. I'd really like to have another contribution credit.

**Comment by arh** [comment]
Thanks, I did submit a code review for your previous PR. Please check it out

**Comment by dahifi** [comment]
Sorry, I must have missed them. I blew out the original repo, so I'm guessing they got deleted along with it. I'm spending a bit more time looking at the way the module is set up. I've been focusing a lot on TDD lately, but not used to mocking, stubbing and dependency injecting stuff for API work. 

Working branch here, I'm going to see if I can increase coverage a bit more. https://github.com/dahifi/tdameritrade/commit/5efcf93281ca07f5d7f67e8e9e3875ac58c573fc

**Comment by dahifi** [comment]
@arh, please take a look at https://github.com/dahifi/tdameritrade/commit/59976b1ae2098e6d3efbe58844afae3fcedc5b21. I ran `make tests` and `coverage report`, but it doesn't seem that increased coverage on the client.py file, just the tests themselves. A quick look at the PR shows way too many changes, so I need to go back and look at whether my resync to your library worked the way I wanted.

**Comment by jd-bartlett96** [comment]
I got the orders endpoint to work by adding a "Content-Type" header and sending the json order input to the "data" parameter rather than the "json" parameter in the request call. The response isn't a json, just the response code (202 if your order is successfully placed):

`    def orders(self, account_id, order):
        ordhead = self._headers().copy()
        ordhead['Content-Type'] = 'application/json'
        return requests.post(ACCOUNTS + account_id + "/orders",
                             headers=ordhead,
                             data=order)`

This resolved the 'A validation error occurred while processing the request.' issue for me

**Comment by Ayers-Kendall** [comment]
> I got the orders endpoint to work by adding a "Content-Type" header and sending the json order input to the "data" parameter rather than the "json" parameter in the request call. The response isn't a json, just the response code (202 if your order is successfully placed):
> 
> `
> 
> `def orders(self, account_id, order):
> 
> ```
> ordhead = self._headers().copy()
> 
> ordhead['Content-Type'] = 'application/json'
> 
> return requests.post(ACCOUNTS + account_id + "/orders",
> 					headers=ordhead,
> 					data=order)`
> ```
> 
> This resolved the 'A validation error occurred while processing the request.' issue for me

Saved me a lot of time. Thank you!

**Comment by timkpaine** [comment]
#60
