### ISSUE TITLE
Getting error pip installing

### ISSUE THREAD

**Issue by wlblount** [timkpaine/tdameritrade#41]
Warning: 'classifiers' should be a list, got type 'filter'
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    
    ----------------------------------------  

Failed building wheel for ujson
Command "C:\Users\EG_User\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\EG_User\\AppData\\Local\\Temp\\pip-install-f70g4ds8\\ujson\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\EG_User\AppData\Local\Temp\pip-record-25_1y43o\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\EG_User\AppData\Local\Temp\pip-install-f70g4ds8\ujson\

I installed Visual C ++ 14 but still same error

**Comment by timkpaine** [comment]
The error is coming from the `ujson` package.
