### ISSUE TITLE
TOKEN HANDLING: Changes to the TDClient class interface parameters 

### ISSUE THREAD

**Issue by dahifi** [timkpaine/tdameritrade#52]
I wanted to discuss things with others before I submit this next PR, as it will break everyone's existing scripts, and I wanted to see if anyone had other suggestions as to how we could fix this.

Currently, we all have to get the access token through the authentication module, then pass this to the TDClient init call: 
```
class TDClient(object):
    def __init__(self, access_token=None, accountIds=None):
```
There's no way for the client to know when this token has expired, so I usually just run leave my terminal open 24/7 and run the refresh call before running my main function. I'm sure you all have your own ways of dealing with this. https://github.com/timkpaine/tdameritrade/issues/25

Tim and pkout have a branch that they've been working on to fix this problem. https://github.com/timkpaine/tdameritrade/pull/48, but it's pretty far behind master right now. I had a merge earlier this weekend in which I introduced a Session class that subclasses from requests.session and can throw exceptions based on the API response. I've now spent a few hours integrating their changes into master in my own repo here: https://github.com/dahifi/tdameritrade/tree/pkout_merge

The refresh call to the API requires both the token and the client ID, so the new constructor is: 
```
class TDClient(object):
    def __init__(self, client_id=None, refresh_token=None, account_ids=[]):
```
(I also changed accoundIds to account_ids for consistency.) 

So the question is whether you all are comfortable with this change. I hate making changes to a class interface, so I'm asking for feedback.

**Comment by timkpaine** [comment]
im happy with this, so long as both can be omitted and provided as environment variables (useful in deployments like heroku/aws/etc). We can bump to `v0.2.0` or `v1.0.0` to delineate the major change.

**Comment by dahifi** [comment]
I guess the question is how it operates now. I currently have a library wrapper that contains my application logic. This loads the .env files and sets the variable before creating the TDClient instance. 

I don't necessarily like the idea of the client or session having to load their own variables. For now I think we should document that client applications will be responsible for maintaining them, and we can work on a tdameritrade class that manages this. ???
