### ISSUE TITLE
How to request forex symbol such as EUR/USD ?

### ISSUE THREAD

**Issue by tolotrasamuel** [timkpaine/tdameritrade#55]
The EUR/USD spot symbol is EUR/USD.
![image](https://user-images.githubusercontent.com/29230303/78376311-2f4db500-75df-11ea-89e6-e6790f563fe9.png)

But when I run this `history` method, I get nothing,

**Comment by timkpaine** [comment]
looks like you can get a quote for EUR/USD, and its available from the search API, but not the history API. This makes me believe they're not making this data available. Feel free to reach out to the TD help email to ask, if they do provide it an example query would be helpful.
