### ISSUE TITLE
Orders NOT working even w/ #54 fix

### ISSUE THREAD

**Issue by shobnaren** [timkpaine/tdameritrade#56]
Reason:
json is passed as params instead of "json" to the endpoint.

Other workaround:
Found a fix!!!! Try this for your orders function

def orders(self, account_id, order):
ord_headers = self._headers().copy()
ord_headers['Content-Type'] = 'application/json'
return requests.post(ACCOUNTS + account_id + "/orders",
headers=ord_headers,
data=order)

**Comment by shobnaren** [comment]
@dahifi this one prevents order to go thru. 

client.py
=======
     def place_order(self, account_id, json_order):
+        """
+        :param account_id: TDAmeritrade Account number
+        :param json_order: dictionary
+        :return:
+        """
         orders = ACCOUNTS + account_id + "/orders"
         resp = self._request(orders,
                              method="POST",
+                             content_type="application/json",
                              json=json_order)

     def place_order(self, account_id, json_order):
+        """
+        :param account_id: TDAmeritrade Account number
+        :param json_order: dictionary
+        :return:
+        """
         orders = ACCOUNTS + account_id + "/orders"
         resp = self._request(orders,
                              method="POST",
+                             content_type="application/json",
                              json=json_order)


session.py
========

+    def set_content_type(self, content_type=None):
+        if content_type:
+            self._headers.update({'Content-Type': content_type})
+
     def request(self, *args, **kwargs):
         self._refresh_token_if_invalid()
-        return super().request(headers=self._headers, *args, **kwargs)
+        self.set_content_type(kwargs.pop("content_type", None))
+        kwargs['headers'] = self._headers
+        return super().request(*args, **kwargs)

**Comment by dahifi** [comment]
Not sure which commit you're working off of. https://github.com/timkpaine/tdameritrade/pull/54 hasn't been committed to the main branch yet, it's only in my repository right now. I'll have to go and check my production code to see how I'm passing the order details, and see whether I need to update tests.

**Comment by timkpaine** [comment]
this is being reworked
