### ISSUE TITLE
API Expansion

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/tdameritrade#58]
# Accounts and Trading
## ORDERS
- [x] CANCEL_ORDER
- [x] GET_ORDER
- [x] GET_ORDERS_BY_PATH
- [x] GET_ORDER_BY_QUERY
- [x] PLACE_ORDER
- [x] REPLACE_ORDER
- [x] CREATE_SAVED_ORDER
- [x] DELETE_SAVED_ORDER
- [x] GET_SAVED_ORDER
- [x] GET_SAVED_ORDER_BY_PATH
- [x] REPLACE_SAVED_ORDER

## ACCOUNTS
- [x] GET_ACCOUNT
- [x] GET_ACCOUNTS

# AUTHENTICATION
- [ ] ACCESS_TOKEN

# INSTRUMENTS
- [x] SEARCH_INSTRUMENTS
- [x] GET_INSTRUMENT

# MARKET HOURS
- [x] GET_HOURS_FOR_MULTIPLE_MARKETS
- [x] GET_HOURS_FOR_SINGLE_MARKET

# MOVERS
- [x] MOVERS

# OPTION CHAINS
- [x] GET_OPTION_CHAIN

# PRICE HISTORY
- [x] GET_PRICE_HISTORY

# QUOTES
- [x] GET_QUOTE
- [x] GET_QUOTES

# TRANSACTION HISTORY
- [x] GET_TRANSACTION
- [x] GET_TRANSACTIONS

# User Info/Prefs
- [x] GET_PREFERENCES
- [ ] GET_STREAMER_SUBSCRIPTION_KEYS
- [ ] GET_USER_PRINCIPALS
- [x] UPDATE_PREFERENCES

# WATCHLIST
- [x] CREATE_WATCHLIST
- [x] DELETE_WATCHLIST
- [x] GET_WATCHLIST
- [x] GET_WATCHLISTS_MULTIPLE_ACCOUNTS
- [x] GET_WATCHLISTS
- [x] REPLACE_WATCHLIST
- [x] UPDATE_WATCHLIST

**Comment by dahifi** [comment]
Do we want to rename all of the existing TDClient functions to match the API calls? Seems like a good idea for consistency. 

Create saved order is already implemented. 

How do you feel about upping my permissions on this repo, or at least this branch so I can commit directly to it? Maybe enable projects and we can track all of this stuff there at least.
