### ISSUE TITLE
Implement order builder as utility to build order jsons

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/tdameritrade#60]

**Comment by Ayers-Kendall** [comment]
Hey, just got a notification about this as I had commented on a previous order issue. I have been using this. It is very simple and was written in just a few minutes, but I figured I'd share it to get you started if you haven't gotten this far already.

def create_json_order(symbol, quantity, price=None, instruction="Buy", type="MARKET", duration="GOOD_TILL_CANCEL", asset_type="EQUITY", session="NORMAL"):
    # For options -- instruction = "BUY_TO_OPEN", etc...
    #                asset_type = "OPTION"
    # session = "NORMAL" or "SEAMLESS" for duration + EXT (extended hours)
    price = str(price)
    order = {"orderType" : type,
             "session" : session,
             "duration": duration,
             "orderStrategyType": "SINGLE",
             "orderLegCollection": [
             {
                  "instruction": instruction,
                  "quantity": quantity,
                  "instrument": {
                      "symbol": symbol,
                      "assetType": asset_type
                  }
             }
             ]
    }
    if type != 'MARKET':
        order['price'] = price
    if asset_type == 'OPTION':
        order['complexOrderStrategyType'] = "NONE"
    return json.dumps(order)

**Comment by dahifi** [comment]
FYI @Ayers-Kendall, you can wrap your code in triple backticks (`)  to preserve formatting. 

I've got a Quicktype library that I built off of JSON2.0 compliant schema that contains Python objects mapings for all of the Account, Instrument, OrderStrategies, Postitions, Quotes, and Transaction JSON. It's part of a client library I've been using; I'll add it to my fork and submit a PR. 

The function I use: 
```

def prep_order(price, instruction, quantity, symbol):
    order_template = """
            {
              "complexOrderStrategyType": "NONE",
              "orderType": "LIMIT",
              "session": "SEAMLESS",
              "price": 0,
              "duration": "GOOD_TILL_CANCEL",
              "orderStrategyType": "SINGLE",
              "orderLegCollection": [
                {
                  "instruction": "BUY",
                  "quantity": 0,
                  "instrument": {
                    "symbol": "",
                    "assetType": "EQUITY"
                  }
                }
              ]
            }
            """
    order = OrderStrategy.from_dict(json.loads(order_template))
    order.price = price
    order.order_leg_collection[0].instruction = Instruction(instruction)
    order.order_leg_collection[0].quantity = quantity
    order.order_leg_collection[0].instrument.symbol = symbol
    order_dict = order.to_dict()
    no_nulls = {k: v for k, v in order_dict.items() if v is not None}
    return no_nulls


def execute_order(tdclient, account_id, order):
    order = json.dumps(order)
    return tdclient.orders(account_id, order)
```

It's a bit clunky, the template is converted to a python object, attributes are updated, then the object is converted back to a dict, the nulls are dropped then it converted to json. I find accessing the parameters via dot objects easier than dictionary syntax.

**Comment by vishwanthpvr** [comment]
Where do you mention the strike price for an option in the above code?

**Comment by dahifi** [comment]
I don't do options, this is an Equity order. The Options orders have different schema. 

The schema's for all the APIs are available on the relevant [TD Developer pages](https://developer.tdameritrade.com/account-access/apis/post/accounts/%7BaccountId%7D/orders-0)

```
//Option:
{
  "assetType": "'EQUITY' or 'OPTION' or 'INDEX' or 'MUTUAL_FUND' or 'CASH_EQUIVALENT' or 'FIXED_INCOME' or 'CURRENCY'",
  "cusip": "string",
  "symbol": "string",
  "description": "string",
  "type": "'VANILLA' or 'BINARY' or 'BARRIER'",
  "putCall": "'PUT' or 'CALL'",
  "underlyingSymbol": "string",
  "optionMultiplier": 0,
  "optionDeliverables": [
    {
      "symbol": "string",
      "deliverableUnits": 0,
      "currencyType": "'USD' or 'CAD' or 'EUR' or 'JPY'",
      "assetType": "'EQUITY' or 'OPTION' or 'INDEX' or 'MUTUAL_FUND' or 'CASH_EQUIVALENT' or 'FIXED_INCOME' or 'CURRENCY'"
    }
  ]
}
```
