### ISSUE TITLE
Can not install on Pycharm 2019.2

### ISSUE THREAD

**Issue by baomx888** [timkpaine/tdameritrade#63]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\XXX\Anaconda3\python.exe' 'C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\XXX\AppData\Local\Temp\tmp4d46fi46'
       cwd: C:\Users\XXX\AppData\Local\Temp\pycharm-packaging\ujson
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

**Comment by timkpaine** [comment]
You can see pretty clearly the issue doesn't come from this library
