### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by baomx888** [timkpaine/tdameritrade#65]
I have a quick question about connecting to the td. 
Here is my code, 
myApp1 is the name I registered in TD API portal.  
refreshtoken1 is the string I got from https://developer.tdameritrade.com/authentication/apis/post/token-0
myloginID is my trading platform login id.  

`myTDClient = td.TDClient(client_id='myApp1', refreshtoken=refreshtoken1,accountIds='myloginID')`

Here is my error message TypeError: __init__() got an unexpected keyword argument 'client_id'

**Comment by timkpaine** [comment]
theres no `client_id` on the latest released version: https://github.com/timkpaine/tdameritrade/blob/v0.1.0/tdameritrade/client.py#L14

**Comment by baomx888** [comment]
so I still can not use refresh-token yet. Right? Sorry for the confusion. I saw the syntax  in the description.  BTW, is streaming data available?
