### ISSUE TITLE
Option chain endpoint regression

### ISSUE THREAD

**Issue by jrbartola** [timkpaine/tdameritrade#68]
Hi all, hope you are doing well during these times. I recently upgraded my package from v0.0.9 to v0.1.0, and noticed that I am no longer able to supply arguments to the `client.options` method. This breaks my own code so I reverted back to 0.0.9. [Here](https://github.com/timkpaine/tdameritrade/commit/5efcf93281ca07f5d7f67e8e9e3875ac58c573fc#diff-a8a0040b36a8b251a600291d3aa86ff8L94) is the commit that introduced the regression.

I did notice that there is some good work going on regarding a client refactor (which hasn't been released yet) that solves my problem, but I just wanted to make aware the breaking change in v0.1.0 :)

**Comment by timkpaine** [comment]
are your kwargs in this list (on master) https://github.com/timkpaine/tdameritrade/blob/master/tdameritrade/client.py#L264

**Comment by jrbartola** [comment]
> are your kwargs in this list (on master) https://github.com/timkpaine/tdameritrade/blob/master/tdameritrade/client.py#L264

Yep, looks like it
