### ISSUE TITLE
TDClient.hours() ValidationError: -1: An unknown error occurred {}

### ISSUE THREAD

**Issue by dahifi** [timkpaine/tdameritrade#70]
Calling hours with no `market` fails. Looks like the API on this one requires a list to be passed, it doesn't return all markets by default. 

Seems like a good starter issue for anyone wanting to contribute. 

(Low priority on this one, but I think there's a larger problem with the exception codes on this one, I've been meaning to fix it so it returns the actual error message for exceptions like this. )

**Comment by timkpaine** [comment]
yeah I think I just misdocumented the code when I was writing it:
https://developer.tdameritrade.com/market-hours/apis/get/marketdata/hours

like most other apis, they have 2 routes that do the same thing (one encodes the data in the route, one passes as a query arg).

**Comment by dahifi** [comment]
So do we want `market=None` to throw an exception or just default to equities? I think the latter is appropriate.

**Comment by dahifi** [comment]
Nevermind, I assume 'READY' means you already fixed it.

**Comment by timkpaine** [comment]
equities sounds good

**Comment by dahifi** [comment]
Fixed in dev branch.
