### ISSUE TITLE
Better instructions with chromedriver

### ISSUE THREAD

**Issue by Macarse** [timkpaine/tdameritrade#82]
Hello!

I recently started playing with the library and I noticed that for auth the library uses chromedriver.
I fixed my issue by going to https://chromedriver.chromium.org/downloads and installing the dependency on my computer. I was wondering if there is a better way to install that dep. I found https://pypi.org/project/chromedriver_installer/ but I am not sure if it will work since chromedriver depends on the chrome version the user is running :(

Do you have any recommendations for best practices? 

I am happy to update the doc based on the result of this ticket 👍

**Comment by ka05** [comment]
@Macarse I have [created a PR](https://github.com/timkpaine/tdameritrade/pull/81) to help with this issue: [Auth with MFA (Security Questions) #24](https://github.com/timkpaine/tdameritrade/issues/24) 

This PR includes some dependency changes. Among those changes was is the addition of [webdriver-manager](https://github.com/SergeyPirogov/webdriver_manager), a manager that detects the OS and downloads and loads the web driver automatically. 
[see requirements.txt](https://github.com/timkpaine/tdameritrade/blob/21e8436af4bc5a296dab460614c4edc096310ba0/requirements.txt)

**Comment by Macarse** [comment]
@ka05 that works for me. Thanks!
