### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by markmark1** [timkpaine/tdameritrade#84]
getting this error on the auth url

This may be due to a technical error, or the client application may be an attempt to fraudulently access your account. If you believe you’ve received this message in error, please contact the publisher of the client application. For more information on securing your account, please see our security page.

**Comment by markmark1** [comment]
is there a way to use library without logging in for just querying the movers and options etc

**Comment by markmark1** [comment]
>>> tdameritrade.auth.authentication('xxxxx','http://localhost:8080')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tdameritrade' has no attribute 'auth'

**Comment by dahifi** [comment]
You're trying to import from the root project directory. Use `from tdameritrade.tdameritrade import auth`. 

TDA doesn't have a public API, so all requests have to be authenticated. Recent updates to this library will allow you to put your refresh token in an env var and do away with the Chromedriver login process.

**Comment by markmark1** [comment]
How do I get the auth and refresh tokens is not clear from the doc Example

**Comment by timkpaine** [comment]
https://tdameritrade.readthedocs.io/en/latest/index.html#authentication
?

**Comment by markmark1** [comment]
run   tdameritrade.auth.authentication   from a python prompt, with   client_id=consumer_keyand   redirect_uri   from step 4.
  
 This doesn't work   
  

  
  
  

  
  
>

**Comment by timkpaine** [comment]
You need to provide more info if you want help. I suspect this has to do with you not understanding the python import system.

![Screen Shot 2020-04-30 at 11 59 50 AM](https://user-images.githubusercontent.com/3105306/80732302-1ea73680-8ada-11ea-8925-4268a054e627.png)

**Comment by Macarse** [comment]
@markmark1 

that's a function. You will need to run something like:

```
tdameritrade.auth.authentication(client_id="your_consumer_key", redirect_uri="https://localhost:8080")
```

**Comment by markmark1** [comment]
Ok thanks carlos
How about keeping it refreshed
I want to set it and forget and not be constantly  pinged to be logged in

**Comment by Macarse** [comment]
@markmark1 you need to understand how oauth2 works.
The API will return an auth token and a refresh token. The library will take care of updating the auth token with the refresh token for a while, I don't really remember how long the refresh token lasts though.

**Comment by markmark1** [comment]
Carlos Thank you for your help.   
  
  
  

  
  

  
  
>

**Comment by markmark1** [comment]
So this line needs to be there before every time an api call is made   
  
Are there any decorators to do same for functions carlos Tim pls   
  

  
  

  
  
>

**Comment by Macarse** [comment]
@markmark1 depends on what you are doing but I recommend you call auth separately.
Create a separate script to grab the refresh token. 
In a separate script initialize the `TDClient()` with the previous refresh token.

The refresh token will work for some time. Once calls start failing, get a new refresh token.

**Comment by markmark1** [comment]
Are there more examples for this
And placing different options and futures orders Tim

**Comment by kleingeo** [comment]
I am having a similar issue. I used the pip installation method, and form what I can gauge, it seems to be an issue with it not installing all dependencies. 

```python
import tdameritrade.auth as ta
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\Miniconda3\envs\test_env\lib\site-packages\tdameritrade\auth\__init__.py", line 6, in <module>
    from selenium import webdriver
  File "D:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'selenium'

```

**Comment by timkpaine** [comment]
@kleingeo selenium isn't a hard dependency, because its a super heavy dependency. so you need to install it separately.
