### ISSUE TITLE
PyPI Package is Out of Date

### ISSUE THREAD

**Issue by ethanchumley** [timkpaine/tdameritrade#95]
Running `pip install tdameritrade` on a clean local project pulls down an version of the package from PyPI that lists `v.0.1.0` but is not consistent with master or the documentation, and has the outdated authentication scheme.
https://pypi.org/project/tdameritrade/ shows a last updated date of March 20, 2020.

Could you push a package update?

**Comment by realbadbytes** [comment]
If anyone just wants to use the pip version thats currently there, just set ACCESS_TOKEN in environ as well and itll function

**Comment by timkpaine** [comment]
this will be resolved this week barring any additions @dahifi wants to make

**Comment by pkout** [comment]
Let's push this please!
