### ISSUE TITLE
Documentation on First Time Auth workflow

### ISSUE THREAD

**Issue by ChocoShell** [timkpaine/tdameritrade#99]
There should be some documentation around how to authenticate with a tdameritrade account for the first time using the `tdameritrade.auth` module.

**Comment by timkpaine** [comment]
I thought it covered all the steps https://tdameritrade.readthedocs.io/en/latest/#authentication

**Comment by ChocoShell** [comment]
Oh! It is covered there.  I saw the first part and thought it had been skipped over since the notebooks starts with just the refresh side. Oops.
